/* 
 * SMS Fusion API
 *
 * This is the SMS Fusion API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@smsfusion.com.au
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing HLRApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class HLRApiTests
    {
        private HLRApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new HLRApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HLRApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' HLRApi
            //Assert.IsInstanceOfType(typeof(HLRApi), instance, "instance is a HLRApi");
        }

        
        /// <summary>
        /// Test GetHLR
        /// </summary>
        [Test]
        public void GetHLRTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string key = null;
            //string num = null;
            //string cc = null;
            //var response = instance.GetHLR(key, num, cc);
            //Assert.IsInstanceOf<HLRCallback> (response, "response is HLRCallback");
        }
        
        /// <summary>
        /// Test GetHLRCallback
        /// </summary>
        [Test]
        public void GetHLRCallbackTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string key = null;
            //List<string> num = null;
            //string cb = null;
            //string cc = null;
            //var response = instance.GetHLRCallback(key, num, cb, cc);
            //Assert.IsInstanceOf<HLRResult> (response, "response is HLRResult");
        }
        
    }

}
