/* 
 * SMS Fusion API
 *
 * This is the SMS Fusion API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@smsfusion.com.au
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SMSApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class SMSApiTests
    {
        private SMSApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new SMSApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SMSApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' SMSApi
            //Assert.IsInstanceOfType(typeof(SMSApi), instance, "instance is a SMSApi");
        }

        
        /// <summary>
        /// Test SendSMS
        /// </summary>
        [Test]
        public void SendSMSTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string key = null;
            //List<string> num = null;
            //string msg = null;
            //string from = null;
            //string deliverby = null;
            //string dlrcb = null;
            //string replycb = null;
            //string replyemail = null;
            //int? validity = null;
            //string cc = null;
            //var response = instance.SendSMS(key, num, msg, from, deliverby, dlrcb, replycb, replyemail, validity, cc);
            //Assert.IsInstanceOf<SMSResult> (response, "response is SMSResult");
        }
        
    }

}
