/* 
 * SMS Fusion API
 *
 * This is the SMS Fusion API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@smsfusion.com.au
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace IO.Swagger.Model
{
    /// <summary>
    /// HLRResult
    /// </summary>
    [DataContract]
    public partial class HLRResult :  IEquatable<HLRResult>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HLRResult" /> class.
        /// </summary>
        /// <param name="Status">Status.</param>
        /// <param name="Success">Success.</param>
        /// <param name="Failure">Failure.</param>
        /// <param name="Cost">Cost of the response.</param>
        /// <param name="Callback">Callback URL provided.</param>
        public HLRResult(string Status = default(string), List<long?> Success = default(List<long?>), List<long?> Failure = default(List<long?>), float? Cost = default(float?), string Callback = default(string))
        {
            this.Status = Status;
            this.Success = Success;
            this.Failure = Failure;
            this.Cost = Cost;
            this.Callback = Callback;
        }
        
        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name="status", EmitDefaultValue=false)]
        public string Status { get; set; }
        /// <summary>
        /// Gets or Sets Success
        /// </summary>
        [DataMember(Name="success", EmitDefaultValue=false)]
        public List<long?> Success { get; set; }
        /// <summary>
        /// Gets or Sets Failure
        /// </summary>
        [DataMember(Name="failure", EmitDefaultValue=false)]
        public List<long?> Failure { get; set; }
        /// <summary>
        /// Cost of the response
        /// </summary>
        /// <value>Cost of the response</value>
        [DataMember(Name="cost", EmitDefaultValue=false)]
        public float? Cost { get; set; }
        /// <summary>
        /// Callback URL provided
        /// </summary>
        /// <value>Callback URL provided</value>
        [DataMember(Name="callback", EmitDefaultValue=false)]
        public string Callback { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class HLRResult {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Success: ").Append(Success).Append("\n");
            sb.Append("  Failure: ").Append(Failure).Append("\n");
            sb.Append("  Cost: ").Append(Cost).Append("\n");
            sb.Append("  Callback: ").Append(Callback).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as HLRResult);
        }

        /// <summary>
        /// Returns true if HLRResult instances are equal
        /// </summary>
        /// <param name="other">Instance of HLRResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(HLRResult other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Status == other.Status ||
                    this.Status != null &&
                    this.Status.Equals(other.Status)
                ) && 
                (
                    this.Success == other.Success ||
                    this.Success != null &&
                    this.Success.SequenceEqual(other.Success)
                ) && 
                (
                    this.Failure == other.Failure ||
                    this.Failure != null &&
                    this.Failure.SequenceEqual(other.Failure)
                ) && 
                (
                    this.Cost == other.Cost ||
                    this.Cost != null &&
                    this.Cost.Equals(other.Cost)
                ) && 
                (
                    this.Callback == other.Callback ||
                    this.Callback != null &&
                    this.Callback.Equals(other.Callback)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Status != null)
                    hash = hash * 59 + this.Status.GetHashCode();
                if (this.Success != null)
                    hash = hash * 59 + this.Success.GetHashCode();
                if (this.Failure != null)
                    hash = hash * 59 + this.Failure.GetHashCode();
                if (this.Cost != null)
                    hash = hash * 59 + this.Cost.GetHashCode();
                if (this.Callback != null)
                    hash = hash * 59 + this.Callback.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
